MultiFileUpload/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fileupload.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fileupload/urls.py
from django.urls import path
from . import views

app_name = "fileupload"

urlpatterns = [
    path('', views.FileUploadView.as_view(), name='upload'),
    path('clear_database/', views.clear_database, name='clear_database'),
]

fileupload/models.py
from django.db import models


class Files(models.Model):
    file = models.FileField(upload_to='Files/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.file.url

    class Meta:
        verbose_name_plural = "Files"

fileupload/forms.py
from django import forms
from .models import Files


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = Files
        fields = ('file', )

fileupload/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import View
from .forms import FileUploadForm
from .models import Files


class FileUploadView(View):
    def get(self, request):
        file_list = Files.objects.all().order_by('-id')

        context = {
            'files': file_list,
        }
        return render(self.request, 'upload/basic_upload.html', context)

    def post(self, request):
        form = FileUploadForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            upload = form.save()
            data = {'is_valid': True, 'name': upload.file.name,
                    'url': upload.file.url, 'upload_time': upload.uploaded_at}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


def clear_database(request):
    for f in Files.objects.all():
        f.file.delete()
        f.delete()
    return redirect(request.POST.get('next'))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}File Library{% endblock %}</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style type="text/css">
    .page-header {
      margin-top: 0;
    }
  </style>
</head>

<body>
  {% include 'partials/_header.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% block javascript %}
  {% endblock %}
</body>

</html>

templates/partials/_header.html
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu"
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Multi FileUpload</a>
    </div>
  </div>
</nav>

templates/partials/_progress_modal.html
<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Uploading...</h4>
        </div>
        <div class="modal-body">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
          </div>
        </div>
      </div>
    </div>
  </div>

templates/upload/base.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action="{% url 'fileupload:clear_database' %}">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ request.path }}">
  <button type="submit" class="btn btn-danger pull-right">
    <span class="glyphicon glyphicon-trash"></span> Clear Database
  </button>
</form>
<h1 class="page-header">
  Uploaded Files
</h1>
<div class="row">
  <div class="col-md-12">
    {% block file_content %}
    {% endblock %}
  </div>
</div>
{% endblock %}

templates/upload/basic_upload.html
{% extends 'upload/base.html' %}

{% load static %}

{% block javascript %}
{# JQUERY FILE UPLOAD SCRIPTS #}
<script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

{# RESUMES PAGE SCRIPTS #}
<script src="{% static 'upload/js/progress-bar-upload.js' %}"></script>
{% endblock %}

{% block file_content %}
<div style="margin-bottom: 20px;">
  <button type="button" class="btn btn-primary js-upload-photos">
    <span class="glyphicon glyphicon-cloud-upload"></span> Upload Files
  </button>
  <input id="fileupload" type="file" name="file" multiple style="display: none;"
    data-url="{% url 'fileupload:upload' %}" data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
</div>

<table id="gallery" class="table table-bordered">
  <thead>
    <tr>
      <th>Files</th>
      <th>Upload Time</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in files %}
    <tr>
      <td><a href="{{ obj.file.url }}">{{ obj.file.name }}</a></td>
      <td>{{ obj.uploaded_at|timesince }} ago</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% include 'partials/_progress_modal.html' %}
{% endblock %}